#!/usr/bin/env python3

import argparse
import logging

import requests
from common import run_command, CommandNotSupportedError

def parse_arguments():
    parser = argparse.ArgumentParser(description='device admission client',
                                     formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('-d', '--debug', help='Enable debugging output',
                        default=False, action='store_true')
    parser.add_argument('-s', '--service', help='Service address',
                        default='https://docker.mender.io:8080/api/integrations/0.1/admission/devices')
    parser.add_argument('-n', '--no-verify', help='Skip certificate verification',
                        default=False, action='store_true')
    parser.set_defaults(command='')
    sub = parser.add_subparsers(help='Commands')

    paccept = sub.add_parser('accept', help='Accept device')
    paccept.add_argument('device', help='Device ID')
    paccept.set_defaults(command='accept')

    preject = sub.add_parser('reject', help='Reject device')
    preject.add_argument('device', help='Device ID')
    preject.set_defaults(command='reject')

    pshow = sub.add_parser('show', help='Show device')
    pshow.add_argument('device', help='Device ID')
    pshow.set_defaults(command='show')

    plist = sub.add_parser('list', help='List devices')
    plist.set_defaults(command='list')

    return parser.parse_args()

def dump_device(data, showkey=True):
    logging.debug('device data: %r', data)
    print('device: %s' % data['id'])
    print('    status: %s' % data['status'])
    print('    request time: %s' % data['request_time'])
    print('    attributes:')
    for key, val in data['attributes'].items():
        print('        %s : %s' % (key, val))
    if showkey:
        print('    public key:')
        print(data['key'])

def show_device(opts):
    url = opts.service + '/{}'.format(opts.device)
    rsp = requests.get(url, verify=opts.verify)
    logging.debug("%r", rsp.status_code)

    dump_device(rsp.json())

def list_devices(opts):
    rsp = requests.get(opts.service, verify=opts.verify)
    logging.debug("%r", rsp.status_code)

    for dev in rsp.json():
        dump_device(dev, showkey=False)

def set_device_status(opts, status):
    url = opts.service + '/{}/status'.format(opts.device)
    logging.debug('device URL: %s', url)
    rsp = requests.put(url,
                       verify=opts.verify,
                       json={
                           'status': status
                       })
    logging.debug("%r", rsp.status_code)
    if rsp.content:
        logging.debug('%r', rsp.json())

def main(opts):
    logging.debug('starting...')

    opts.verify = not opts.no_verify

    logging.debug('options: %r', opts)
    try:
        commands = {
            'list': list_devices,
            'accept': lambda o: set_device_status(o, 'accepted'),
            'reject': lambda o: set_device_status(o, 'rejected'),
            'show': show_device,
        }
        run_command(opts.command, commands, opts)
    except requests.exceptions.RequestException as rerr:
        logging.error('request failed: %s', rerr)
    except CommandNotSupportedError:
        logging.error('incomplete or unsupported command, see --help')


if __name__ == '__main__':
    args = parse_arguments()

    level = logging.INFO
    if args.debug:
        level = logging.DEBUG

    logging.basicConfig(level=level)

    main(args)
